

insert into sales_ops.dbo.Churn_Model_Scoring (
  [Accountid]
      ,[Account_Number]
      ,[Raison_Sociale]
      ,[SIRET]
      ,[telephone]
      ,[Etat]
      ,[CommMode]
      ,[Flag_partenaire]
      ,[ProductCode]
      ,[Users]
      ,[numero_serie]
      ,[urn]
      ,[new_nps_notenps]
      ,[DomainStat]
      ,[ProductLine]
      ,[etat_PE]
      ,[date_debut]
      ,[date_fin_contrat]
      ,[date_vente]
      ,[age_client_product]
      ,[Commitment]
      ,[RenewalValue]
      ,[PNPR]
      ,[RegistrationStatus]
      ,[TargetEvent]
      ,[ModeRegelementTier]
      ,[Statut_Paiement_contrat]
      ,[Statut_Paiement_licence]
      ,[ReferenceDate]
      ,[urnfils]
      ,[regcount]
      ,[NumberOfContacts]
      ,[nettvalue_renewal__1]
      ,[nettvalue_renewal__2]
      ,[nettvalue_renewal__3]
      ,[nettvalue_agence__1]
      ,[nettvalue_agence__2]
      ,[nettvalue_agence__3]
      ,[NumberOfComplaints_1Years]
      ,[NumberOfComplaints_2Years]
      ,[adderegsprevyear]
      ,[age_of_customer]
      ,[UK Product Code]
      ,[UK Product Name]
      ,[HFM Name]
      ,[UEL - Year]
      ,[UEL - Month]
      ,[MotifResil]
      ,[UEL.1]
      ,[Product_Line_Stat]
      ,[Domain_Stat]
      ,[Likelihood to Recommend_Mean]
      ,[VersionNo]
      ,[nbreConnexion]
      ,[nb_days]
      ,[VersionNoMax]
      ,[nbreConnexionMax]
      ,[Dif_Version]
      ,[Dif_Nbr_Connexions]
      ,[Connexions_per_day]
      ,[nb_years_since_first_connexion]
      ,[AccountNumber]
      ,[new_note_enquete]
      ,[new_ces_score]
      ,[PreviousRenewalValue]
      ,[Distance_Version]
      ,[new_BU]
      ,[new_Libelle]
      ,[Abonnement]
      ,[Naf_Code]
      ,[Churn_Score]
      ,[ChurnInverse]
      ,[Decile]
      ,vague )


SELECT  [Accountid]
      ,[Account_Number]
      ,[Raison_Sociale]
      ,[SIRET]
      ,[telephone]
      ,[Etat]
      ,[CommMode]
      ,[Flag_partenaire]
      ,[ProductCode]
      ,[Users]
      ,[numero_serie]
      ,[urn]
      ,[new_nps_notenps]
      ,[DomainStat]
      ,[ProductLine]
      ,[etat_PE]
      ,[date_debut]
      ,[date_fin_contrat]
      ,[date_vente]
      ,[age_client_product]
      ,[Commitment]
      ,[RenewalValue]
      ,[PNPR]
      ,[ResitrationStatus]
      ,[TargetEvent]
      ,[ModeRegelementTier]
      ,[Statut_Paiement_contrat]
      ,[Statut_Paiement_licence]
      ,[ReferenceDate]
      ,[urnfils]
      ,[regcount]
      ,[NumberOfContacts]
      ,[nettvalue_renewal__1]
      ,[nettvalue_renewal__2]
      ,[nettvalue_renewal__3]
      ,[nettvalue_agence__1]
      ,[nettvalue_agence__2]
      ,[nettvalue_agence__3]
      ,[NumberOfComplaints_1Years]
      ,[NumberOfComplaints_2Years]
      ,[adderegsprevyear]
      ,[age_of_customer]
      ,[UK Product Code]
      ,[UK Product Name]
      ,[HFM Name]
      ,[UEL - Year]
      ,[UEL - Month]
      ,[MotifResil]
      ,[UEL.1]
      ,[Product_Line_Stat]
      ,[Domain_Stat]
      ,[Likelihood to Recommend_Mean]
      ,[VersionNo]
      ,[nbreConnexion]
      ,[nb_days]
      ,[VersionNoMax]
      ,[nbreConnexionMax]
      ,[Dif_Version]
      ,[Dif_Nbr_Connexions]
      ,[Connexions_per_day]
      ,[nb_years_since_first_connexion]
      ,[AccountNumber]
      ,[new_note_enquete]
      ,[new_ces_score]
      ,[PreviousRenewalValue]
      ,[Distance_Version]
      ,[new_BU]
      ,[new_Libelle]
      ,[Abonnement]
      ,[Naf_Code]
      ,[Churn_Score]
      ,[ChurnInverse]
      ,[Decile]
      ,getdate()
  FROM [SALES_OPS].[dbo].[Temp_Churn_Model_Scoring] 


    ---- Autre facon de créer TEMP---
  -----Copier table et trncate apres---

--SELECT *
--INTO [SALES_OPS].[dbo].[Temp_Churn_Model_Scoring]
--FROM [SALES_OPS].[dbo].[Churn_Model_Scoring]

--truncate table [SALES_OPS].[dbo].[Temp_Churn_Model_Scoring_]

--verif---
--select * from [SALES_OPS].[dbo].[Temp_Churn_Model_Scoring]


--supp tem--
--drop table [SALES_OPS].[dbo].[Temp_Churn_Model_Scoring_mdi]
--drop table [SALES_OPS].[dbo].[Temp_Churn_Model_Scoring_test]